-- require("plugins.themes.tokyonight")
-- require("plugins.themes.everforest")
require("plugins.themes.evergarden")
require("plugins.mini")
require("plugins.oil")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.blink")
require("plugins.snacks")
require("plugins.mason")
