"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """
$os$hostname$username$azure$kubernetes
$git_branch$git_status$git_state$directory
$status
"""

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '
symbol = ' 󰠳 '
style = '#326CE5 bold'

[character]
success_symbol = '[󰘧](bold green)'
error_symbol = '[󰘧](bold red)'

[azure]
disabled = false
format = "[$symbol($subscription)]($style) "
symbol = " 󰠅 "
style = "#008ad7 bold"

[status]
format = '[$symbol\($status\)]($style) '
symbol = ''
disabled = false

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ' '

[directory]
format = '[$read_only]($read_only_style)[$path]($style)'
truncation_length = 0
read_only = '󱪨 '
truncate_to_repo = true
style = 'bold cyan'

[hostname]
format = '[$ssh_symbol$hostname]($style)  '
style = '#1793d1 bold'
ssh_only = false

[username]
format = '[ $user]($style) '
show_always = true
style_user = 'yellow'
style_root = 'red bold'

[os]
format = '$symbol'
disabled = false

[os.symbols]
Arch = '[󰣇](#1793d1 bold) '
